fos_rest:
    allowed_methods_listener: true
    view:
        view_response_listener: true
        formats:
            json: true
    exception:
        codes:
            App\Domain\Shared\Exception\NotFoundException: 404
        messages:
            App\Domain\Shared\Exception\NotFoundException: true
    format_listener:
        rules:
            - { path: ^/, prefer_extension: true, fallback_format: json, priorities: [ json ] }
    body_listener: true
