version: "3"
services:

  nginx:
    image: nginx:1.21
    container_name: demo-app-nginx
    working_dir: /application
    volumes:
      - .:/application
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"

  php:
    build: docker/php
    container_name: demo-app-php
    working_dir: /application
    volumes:
      - .:/application
    user: "1000:1000"

  mariadb:
    image: mariadb:10.6
    container_name: demo-app-mariadb
    environment:
      - MYSQL_DATABASE=demo_app
      - MYSQL_USER=demo_app
      - MYSQL_PASSWORD=demo_app_password
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    ports:
      - "3306:3306"
